name=dual2s
version=2.0.1
author=nick
maintainer=nick <hhchen.sci@gms.ndhu.edu.tw>
sentence=A comprehensive library for ESP32-based GoSUMO and 4WD robots.
paragraph=Supports DC motors, MG995 servos, HC-SR04 ultrasonic sensors, IR tracking, and WS2812B LEDs with non-blocking logic.
category=Device Contro
url=https://github.com/yesio/dual2s
architectures=esp32
includes=dual2s.h
