name=dual2s
version=2.0.2
author=yesio
maintainer=yesio <hhchen.sci@gms.ndhu.edu.tw>
sentence=A multi-purpose library for GoSUMO robots and AIoT projects based on ESP32.
paragraph=Supports WS2812B, Buzzer, Ultrasonic, IR Line Tracking, Servo, DC Motors, and PS3 Controller.
category=Device Contro
url=https://github.com/yesio/dual2s
architectures=esp32
depends=Adafruit NeoPixel, Ps3Controller
